#! /bin/sh

### BEGIN INIT INFO
# Provides:		containerd
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	Apache container server
### END INIT INFO

set -e

# /etc/init.d/containerd: start and stop the Apache Container service

test -x /usr/bin/containerd || exit 0

umask 022

. /lib/lsb/init-functions


# Are we running from init?
run_by_init() {
    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
}


check_dev_null() {
    if [ ! -c /dev/null ]; then
	if [ "$1" = log_end_msg ]; then
	    log_end_msg 1 || true
	fi
	if ! run_by_init; then
	    log_action_msg "/dev/null is not a character device!" || true
	fi
	exit 1
    fi
}


export PATH="${PATH:+$PATH:}/usr/bin:/bin"

case "$1" in
  start)
	check_dev_null
	log_daemon_msg "Starting Apache Container server" "containerd" || true
	if start-stop-daemon --start --background --quiet --oknodo --chuid 0:0 --pidfile /run/containerd.pid --exec /usr/bin/containerd; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
  stop)
	log_daemon_msg "Stopping Apache Container server" "containerd" || true
	if start-stop-daemon --stop --quiet --oknodo --pidfile /run/containerd.pid --exec /usr/bin/containerd; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  reload|force-reload)
	check_for_no_start
	log_daemon_msg "Reloading Apache Container server's configuration" "containerd" || true
	if start-stop-daemon --stop --signal 1 --quiet --oknodo --pidfile /run/containerd.pid --exec /usr/bin/containerd; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  restart)
	log_daemon_msg "Restarting Apache Container server" "sshd" || true
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile /run/containerd.pid --exec /usr/bin/containerd
	check_dev_null log_end_msg
	if start-stop-daemon --start --background --quiet --oknodo --chuid 0:0 --pidfile /run/containerd.pid --exec /usr/bin/containerd; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  try-restart)
	log_daemon_msg "Restarting Apache Container server" "sshd" || true
	RET=0
	start-stop-daemon --stop --quiet --retry 30 --pidfile /run/containerd.pid --exec /usr/bin/containerd || RET="$?"
	case $RET in
	    0)
		# old daemon stopped
		check_dev_null log_end_msg
		if start-stop-daemon --start --background --quiet --oknodo --chuid 0:0 --pidfile /run/containerd.pid --exec /usr/bin/containerd; then
		    log_end_msg 0 || true
		else
		    log_end_msg 1 || true
		fi
		;;
	    1)
		# daemon not running
		log_progress_msg "(not running)" || true
		log_end_msg 0 || true
		;;
	    *)
		# failed to stop
		log_progress_msg "(failed to stop)" || true
		log_end_msg 1 || true
		;;
	esac
	;;

  status)
	status_of_proc -p /run/containerd.pid /usr/bin/containerd containerd && exit 0 || exit $?
	;;

  *)
	log_action_msg "Usage: /etc/init.d/container {start|stop|reload|force-reload|restart|try-restart|status}" || true
	exit 1
esac

exit 0
